#!/usr/bin/env bash
#
# File:         bootstrap
# Description:  Install ruby, rvm, bundler, and gems. 

MYSELF=`basename $0`
MY_DIR=`echo $(cd $(dirname $0); pwd)`
. $MY_DIR/sh/common.sh

print_usage() {
  echo "Usage: $MYSELF [--skip-ruby|-h]"
  echo
  echo "    --skip-ruby                      Do not bootstrap Ruby/rvm/bundler/gems."
  echo "    -h, --help                       Print this help message and exit."
}

skip_ruby=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-ruby)
      skip_ruby=1
      shift
      ;;
    -h|--help)
      print_usage
      exit 98
      ;;
    *)
      error "Unexpected option ${1}"
      echo
      print_usage
      exit 99
      ;;
  esac
done


puts "+---------------------------+"
puts "| BOOTSTRAPPING DEPLOY |"
puts "+---------------------------+"



###
### Ruby
###
if [ $skip_ruby -eq 1 ]; then
    puts "Skipping prepration of Ruby environment.  You must take care of this manually!"
else
    puts "Preparing Ruby environment..."
    curl -L https://raw.githubusercontent.com/miguno/ruby-bootstrap/master/ruby-bootstrap.sh | bash -s
fi

# Ensure this terminal session knows about rvm
RVM_SCRIPT="$HOME/.rvm/scripts/rvm" # Note: Do not use `~`, stick with `$HOME`
[[ -s "$RVM_SCRIPT" ]] && source $RVM_SCRIPT




